table fact_bookings
	lineageTag: 5156d9e8-3b11-491f-b95e-1e2cdf147cef

	column booking_id
		dataType: string
		lineageTag: 6cf36bc4-7c68-48b2-ad57-96f6691809db
		summarizeBy: none
		sourceColumn: booking_id

	column property_id
		dataType: int64
		formatString: 0
		lineageTag: d6314bc2-46fc-4eaa-958e-d31491bf365b
		summarizeBy: none
		sourceColumn: property_id

	column booking_date
		dataType: dateTime
		formatString: Long Date
		lineageTag: b71813e3-b771-4022-b1f6-0327f551cc4e
		summarizeBy: none
		sourceColumn: booking_date

	column check_in_date
		dataType: dateTime
		formatString: Long Date
		lineageTag: dc99bcd9-bb2d-4113-8b72-6b8468f2cafd
		summarizeBy: none
		sourceColumn: check_in_date

	column checkout_date
		dataType: dateTime
		formatString: Long Date
		lineageTag: b07255ee-efeb-4cc0-9452-4a7ce36b2f70
		summarizeBy: none
		sourceColumn: checkout_date

	column no_guests
		dataType: int64
		formatString: 0
		lineageTag: cc1e059e-4464-4dc5-8567-5b5166933a00
		summarizeBy: sum
		sourceColumn: no_guests

	column room_category
		dataType: string
		lineageTag: 1c1f7068-ee8d-4d93-a8ff-c9d046484815
		summarizeBy: none
		sourceColumn: room_category

	column booking_platform
		dataType: string
		lineageTag: 3ebc9bbb-9dc3-4fb3-bcbe-dcf7d652946c
		summarizeBy: none
		sourceColumn: booking_platform

	column ratings_given
		dataType: double
		lineageTag: 812b6354-1471-445f-8b07-f67431b268e3
		summarizeBy: average
		sourceColumn: ratings_given

	column booking_status
		dataType: string
		lineageTag: 282782ba-bb86-4bf8-a3c4-343139df982c
		summarizeBy: none
		sourceColumn: booking_status

	column revenue_generated
		dataType: int64
		formatString: 0
		lineageTag: adc7203c-628a-49e2-a0ce-545b6bc418e6
		summarizeBy: sum
		sourceColumn: revenue_generated

	column revenue_realized
		dataType: int64
		formatString: 0
		lineageTag: 5a985a5f-a52e-4b90-a139-d76866350492
		summarizeBy: sum
		sourceColumn: revenue_realized

	partition fact_bookings = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(DataFolderPath & "\fact_bookings.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    ChangedType = Table.TransformColumnTypes(Promoted, {{"booking_id", type text}, {"property_id", Int64.Type}, {"booking_date", type date}, {"check_in_date", type date}, {"checkout_date", type date}, {"no_guests", Int64.Type}, {"room_category", type text}, {"booking_platform", type text}, {"ratings_given", type number}, {"booking_status", type text}, {"revenue_generated", Int64.Type}, {"revenue_realized", Int64.Type}})
				in
				    ChangedType

	annotation PBI_ResultType = Table

