table fact_aggregated_bookings
	lineageTag: 7f6e1ccb-0f79-4ff2-9143-1fcbe93d9819

	column property_id
		dataType: int64
		formatString: 0
		lineageTag: 3b1e27f8-c7c6-4aeb-8dbb-55f745eb9675
		summarizeBy: none
		sourceColumn: property_id

	column check_in_date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 6e0316ea-110f-4f0a-ba19-0aa3fa5c62b5
		summarizeBy: none
		sourceColumn: check_in_date

	column room_category
		dataType: string
		lineageTag: dc535a25-b676-4e7d-b64b-732816100794
		summarizeBy: none
		sourceColumn: room_category

	column successful_bookings
		dataType: int64
		formatString: 0
		lineageTag: bbfb04c6-511e-4a89-8610-6156b143419f
		summarizeBy: sum
		sourceColumn: successful_bookings

	column capacity
		dataType: int64
		formatString: 0
		lineageTag: c8c3a69d-bf31-4d2d-a6ca-f2563159bed7
		summarizeBy: sum
		sourceColumn: capacity

	partition fact_aggregated_bookings = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(DataFolderPath & "\fact_aggregated_bookings.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    Parsed = Table.TransformColumns(Promoted, {{"check_in_date", each Date.FromText(_, [Format="dd-MMM-yy", Culture="en-US"]), type date}}),
				    ChangedType = Table.TransformColumnTypes(Parsed, {{"property_id", Int64.Type}, {"check_in_date", type date}, {"room_category", type text}, {"successful_bookings", Int64.Type}, {"capacity", Int64.Type}})
				in
				    ChangedType

	annotation PBI_ResultType = Table

